name: Notifications CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      mongo:
        image: mongo:6
        ports:
          - 27017:27017

    env:
      MONGO_CONNECTION_STRING: mongodb://localhost:27017
      MONGO_DATABASE_NAME: notifications_db
      EMAIL_ENABLED: "false"
      SENDGRID_API_KEY: ${{ secrets.SENDGRID_API_KEY }}
      SENDGRID_FROM_EMAIL: ${{ secrets.SENDGRID_FROM_EMAIL }}

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install deps
        run: |
          pip install -r requirements.txt

      - name: Start API
        run: |
          python -m uvicorn src.notifications.app:app --host 127.0.0.1 --port 8000 &
          sleep 5

      - name: Set PYTHONPATH
        run: |
          echo "PYTHONPATH=$(pwd)" >> $GITHUB_ENV

      - name: Run tests
        run: |
          python -m pytest tests/test_api_v2.py -v
    
      - name: Install JS test dependencies
        run: |
          cd tests-js
          npm install

      - name: Run JS API tests (Jest)
        run: |
          cd tests-js
          npm test